# Build stage
FROM node:alpine AS build

WORKDIR /backend

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Production stage
FROM node:alpine

ARG MICROSOFT_CLIENT_SECRET=NONE
ARG GOOGLE_CLIENT_SECRET=NONE
ARG GOOGLE_CLIENT_ID=NONE
ARG MONGO_URI=NONE
ENV MICROSOFT_CLIENT_SECRET=$MICROSOFT_CLIENT_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV MONGO_URI=$MONGO_URI

WORKDIR /backend

COPY --from=build /backend/package*.json ./
COPY --from=build /backend/node_modules ./node_modules
COPY --from=build /backend/dist ./dist

EXPOSE 5000

CMD ["node", "dist/index.js"]
